import { CourtHearing, PocketCase, JudicialContact, VoiceNote } from '../types';

export const initialHearings: CourtHearing[] = [
  {
    id: 'hear-001',
    caseNumber: '24/01482',
    roleNumber: 4,
    jurisdiction: "Tribunal de Sidi M'hamed",
    jurisdictionAr: 'محكمة سيدي امحمد',
    chamber: 'Chambre Immobilière',
    chamberAr: 'الغرفة العقارية',
    courtroom: 'Salle 02',
    judge: 'Président Mansouri',
    clientName: 'Belkacem Hamoudi',
    clientPhone: '+213 550 12 34 56',
    opposingParty: 'SARL Hydra Promotion',
    opposingCounsel: 'Me Chergui Abdelkader',
    date: '2026-10-10',
    time: '09:00',
    status: 'pending',
    syncStatus: 'synced',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'hear-002',
    caseNumber: '24/00891',
    roleNumber: 11,
    jurisdiction: "Tribunal de Sidi M'hamed",
    jurisdictionAr: 'محكمة سيدي امحمد',
    chamber: 'Chambre des Référés',
    chamberAr: 'غرفة الاستعجالي',
    courtroom: 'Salle 01',
    judge: 'Présidente Bensalem',
    clientName: 'Amina Benali',
    clientPhone: '+213 661 78 90 12',
    opposingParty: 'EURL Travaux Centre',
    opposingCounsel: 'Me Larbi Youcef',
    date: '2026-10-10',
    time: '09:30',
    status: 'pending',
    syncStatus: 'synced',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'hear-003',
    caseNumber: '23/04105',
    roleNumber: 7,
    jurisdiction: "Cour d'Alger (Ruisseau)",
    jurisdictionAr: 'مجلس قضاء الجزائر (رويسو)',
    chamber: 'Chambre Sociale',
    chamberAr: 'الغرفة الاجتماعية',
    courtroom: 'Salle 06',
    judge: 'Conseiller Touati',
    clientName: 'Mourad Bouzid',
    clientPhone: '+213 770 45 67 89',
    opposingParty: 'SPA Logistique Maghreb',
    opposingCounsel: 'Me Benmansour H.',
    date: '2026-10-10',
    time: '10:00',
    status: 'pending',
    syncStatus: 'synced',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'hear-004',
    caseNumber: '24/02319',
    roleNumber: 19,
    jurisdiction: "Cour d'Alger (Ruisseau)",
    jurisdictionAr: 'مجلس قضاء الجزائر (رويسو)',
    chamber: 'Chambre Commerciale',
    chamberAr: 'الغرفة التجارية',
    courtroom: 'Salle 08',
    judge: 'Conseiller Brahimi',
    clientName: "SARL Parfums d'Orient",
    clientPhone: '+213 555 33 22 11',
    opposingParty: 'Société Al-Andalous Distribution',
    opposingCounsel: 'Me Ouali Rachid',
    date: '2026-10-10',
    time: '10:30',
    status: 'postponed',
    outcomeNotes: 'تأجيل للاطلاع على تقرير الخبرة الحسابية المودع حديثاً',
    nextHearingDate: '2026-10-24',
    nextHearingReason: 'Réplique sur conclusions après expertise',
    syncStatus: 'synced',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'hear-005',
    caseNumber: '24/00412',
    roleNumber: 23,
    jurisdiction: "Tribunal de Sidi M'hamed",
    jurisdictionAr: 'محكمة سيدي امحمد',
    chamber: 'Chambre Civile',
    chamberAr: 'الغرفة المدنية',
    courtroom: 'Salle 04',
    judge: 'Président Kaci',
    clientName: 'Ets Chahid & Frères',
    clientPhone: '+213 660 99 88 77',
    opposingParty: 'Khaled Benaissa',
    opposingCounsel: 'Me Belhadj Samia',
    date: '2026-10-10',
    time: '11:00',
    status: 'deliberation',
    outcomeNotes: 'حجز القضية للنطق بالحكم في جلسة 17 أكتوبر 2026',
    nextHearingDate: '2026-10-17',
    nextHearingReason: 'Mise en délibéré pour jugement',
    syncStatus: 'synced',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'hear-006',
    caseNumber: '24/03120',
    roleNumber: 31,
    jurisdiction: "Tribunal de Sidi M'hamed",
    jurisdictionAr: 'محكمة سيدي امحمد',
    chamber: 'Chambre Correctionnelle',
    chamberAr: 'غرفة الجنح',
    courtroom: 'Salle 03',
    judge: 'Président Derradji',
    clientName: 'Karim Meziane',
    clientPhone: '+213 561 22 44 66',
    opposingParty: 'Ministère Public / Partie Civile',
    date: '2026-10-10',
    time: '11:45',
    status: 'pleaded',
    outcomeNotes: 'تمت المرافعة وتقديم الدفوع الشكلية بعدم الاختصاص الإقليمي',
    nextHearingDate: '2026-10-24',
    nextHearingReason: 'Délibéré sur l’exception d’incompétence',
    syncStatus: 'synced',
    updatedAt: new Date().toISOString(),
  },
];

export const initialCases: PocketCase[] = [
  {
    id: 'case-001',
    reference: 'SLIM-2024-001',
    roleNumber: '04',
    title: 'Litige Foncier — Droit de Copropriété et Servitude',
    titleAr: 'نزاع عقاري — ملكية مشتركة وحق ارتفاق',
    clientName: 'Belkacem Hamoudi',
    clientPhone: '+213 550 12 34 56',
    clientEmail: 'b.hamoudi@algerie-affaires.dz',
    opposingParty: 'SARL Hydra Promotion',
    jurisdiction: "Tribunal de Sidi M'hamed",
    jurisdictionAr: 'محكمة سيدي امحمد',
    chamber: 'Chambre Immobilière',
    stage: 'Conclusions responsives',
    nextHearingDate: '2026-10-10',
    courtroom: 'Salle 02',
    claimAmountDzd: 18500000,
    lastNotes: 'Expertise géomètre déposée le 15 Septembre. Conclure à l’annulation du plan.',
    syncStatus: 'synced',
  },
  {
    id: 'case-002',
    reference: 'SLIM-2024-002',
    roleNumber: '11',
    title: 'Référé d’Heure à Heure — Arrêt Immédiat de Démolition',
    titleAr: 'دعوى استعجالية من ساعة لأخرى — وقف أشغال الهدم',
    clientName: 'Amina Benali',
    clientPhone: '+213 661 78 90 12',
    opposingParty: 'EURL Travaux Centre',
    jurisdiction: "Tribunal de Sidi M'hamed",
    jurisdictionAr: 'محكمة سيدي امحمد',
    chamber: 'Chambre des Référés',
    stage: 'Plaidoirie en référé',
    nextHearingDate: '2026-10-10',
    courtroom: 'Salle 01',
    claimAmountDzd: 3200000,
    lastNotes: 'Constat d’huissier établi par Me Khelifi avec photos certifiées.',
    syncStatus: 'synced',
  },
  {
    id: 'case-003',
    reference: 'SLIM-2023-089',
    roleNumber: '07',
    title: 'Appel — Licenciement Abusif Cadre Supérieur',
    titleAr: 'استئناف — تسريح تعسفي لإطار سامي',
    clientName: 'Mourad Bouzid',
    clientPhone: '+213 770 45 67 89',
    opposingParty: 'SPA Logistique Maghreb',
    jurisdiction: "Cour d'Alger (Ruisseau)",
    jurisdictionAr: 'مجلس قضاء الجزائر (رويسو)',
    chamber: 'Chambre Sociale',
    stage: 'Débats au fond',
    nextHearingDate: '2026-10-10',
    courtroom: 'Salle 06',
    claimAmountDzd: 9600000,
    lastNotes: 'Demander l’indemnité de préavis et 24 mois de salaire selon Loi 90-11.',
    syncStatus: 'synced',
  },
  {
    id: 'case-004',
    reference: 'SLIM-2024-019',
    roleNumber: '19',
    title: 'Action en Contrefaçon de Marque & Concurrence Déloyale',
    titleAr: 'دعوى تقليد علامة تجارية ومنافسة غير مشروعة',
    clientName: "SARL Parfums d'Orient",
    clientPhone: '+213 555 33 22 11',
    opposingParty: 'Société Al-Andalous Distribution',
    jurisdiction: "Cour d'Alger (Ruisseau)",
    jurisdictionAr: 'مجلس قضاء الجزائر (رويسو)',
    chamber: 'Chambre Commerciale',
    stage: 'Mise en état après expertise',
    nextHearingDate: '2026-10-24',
    courtroom: 'Salle 08',
    claimAmountDzd: 45000000,
    lastNotes: 'Rapport INAPI attestant du dépôt exclusif en 2021.',
    syncStatus: 'synced',
  },
  {
    id: 'case-005',
    reference: 'SLIM-2024-031',
    roleNumber: '31',
    title: 'Défense Pénale — Abus de Confiance & Escroquerie',
    titleAr: 'دفاع جنائي — جنحة النصب وخيانة الأمانة',
    clientName: 'Karim Meziane',
    clientPhone: '+213 561 22 44 66',
    opposingParty: 'Partie Civile B.M.',
    jurisdiction: "Tribunal de Sidi M'hamed",
    jurisdictionAr: 'محكمة سيدي امحمد',
    chamber: 'Chambre Correctionnelle',
    stage: 'Plaidoirie',
    nextHearingDate: '2026-10-10',
    courtroom: 'Salle 03',
    lastNotes: 'Plaidoyer sur le défaut d’élément intentionnel et la nature purement civile de la transaction.',
    syncStatus: 'synced',
  },
];

export const initialContacts: JudicialContact[] = [
  {
    id: 'cont-001',
    name: 'Me Tarek Khelifi',
    nameAr: 'الأستاذ طارق خليفي',
    type: 'bailiff',
    phone: '+213 550 88 11 22',
    whatsapp: '+213550881122',
    jurisdiction: "Sidi M'hamed & Alger Centre",
    officeAddress: '12 Rue Didouche Mourad, Alger',
    isAvailableForSubstitution: true,
    speciality: 'Constat d’urgence & Signification des assignations',
    avatarInitials: 'TK',
  },
  {
    id: 'cont-002',
    name: 'Me Nadia Boumedienne',
    nameAr: 'الأستاذة نادية بومدين',
    type: 'bailiff',
    phone: '+213 661 44 33 22',
    whatsapp: '+213661443322',
    jurisdiction: 'Bir Mourad Raïs & El Biar',
    officeAddress: '05 Boulevard des Martyrs, Alger',
    isAvailableForSubstitution: true,
    speciality: 'Exécution forcée des arrêts & Saisies conservatoires',
    avatarInitials: 'NB',
  },
  {
    id: 'cont-003',
    name: 'Me Salim Amrani',
    nameAr: 'الأستاذ سليم عمراني',
    type: 'colleague',
    phone: '+213 770 12 99 88',
    whatsapp: '+213770129988',
    jurisdiction: "Cour d'Alger (Ruisseau)",
    officeAddress: 'Cour d’Alger, Salle des Avocats',
    isAvailableForSubstitution: true,
    speciality: 'Chambre Sociale & Commerciale (Disponible pour Énaaba)',
    avatarInitials: 'SA',
  },
  {
    id: 'cont-004',
    name: 'Me Lynda Cherif',
    nameAr: 'الأستاذة ليندة شريف',
    type: 'colleague',
    phone: '+213 555 77 66 55',
    whatsapp: '+213555776655',
    jurisdiction: "Tribunal de Sidi M'hamed",
    officeAddress: 'Ordre des Avocats, Palais de Justice',
    isAvailableForSubstitution: true,
    speciality: 'Chambre Référés & Civile (Présente Salle 02)',
    avatarInitials: 'LC',
  },
  {
    id: 'cont-005',
    name: 'Dr. Amar Zerrouki',
    nameAr: 'الدكتور عمار زروقي',
    type: 'expert',
    phone: '+213 661 22 55 88',
    whatsapp: '+213661225588',
    jurisdiction: 'Cour d’Alger (Toutes juridictions)',
    officeAddress: 'Bab Ezzouar, Alger',
    isAvailableForSubstitution: false,
    speciality: 'Expert Judiciaire Foncier & Travaux Publics',
    avatarInitials: 'AZ',
  },
];

export const initialVoiceNotes: VoiceNote[] = [
  {
    id: 'voice-001',
    caseReference: 'SLIM-2024-001',
    hearingId: 'hear-001',
    title: "Audience Sidi M'hamed — Hamoudi c/ Hydra",
    timestamp: '2026-10-10 09:42',
    durationSeconds: 42,
    audioUri: 'file://storage/audio_note_001.m4a',
    transcription: "Plaidoirie effectuée en Salle 02 devant le Président Mansouri. Dépôt de nos conclusions additionnelles rejetant la servitude revendiquée par la partie adverse. L'affaire a été mise en délibéré pour prononcé du jugement au 24 Octobre 2026.",
    transcriptionAr: 'تمت المرافعة بالقاعة 02 أمام الرئيس منصوري وإيداع المذكرة التكميلية. حجزت القضية للنطق بالحكم بتاريخ 24 أكتوبر 2026.',
    tags: ["Sidi M'hamed", 'Rôle 04', 'Délibéré', 'Immobilier'],
    syncStatus: 'synced',
  },
  {
    id: 'voice-002',
    caseReference: 'SLIM-2024-002',
    hearingId: 'hear-002',
    title: 'Référé d’Heure à Heure — Benali c/ EURL Travaux',
    timestamp: '2026-10-10 10:15',
    durationSeconds: 28,
    audioUri: 'file://storage/audio_note_002.m4a',
    transcription: "Présidente Bensalem a accordé l'ordonnance d'arrêt immédiat des travaux de démolition sous astreinte de 50.000 DA par jour de retard. Contacter Me Khelifi immédiatement pour la délivrance de la grosse.",
    transcriptionAr: 'أصدرت رئيسة الاستعجالي أمراً بوقف الأشغال تحت غرامة تهديدية قدرها 50 ألف دج عن كل يوم تأخير. تكليف المحضر خليفي بسحب الصيغة فوراً.',
    tags: ['Référé', 'Astreinte', 'Huissier', 'Ordonnance'],
    syncStatus: 'synced',
  },
];
